### ISSUE TITLE
Encoding issue in tt/header.tt output

### ISSUE THREAD

**Issue by burak** [petdance/bobby-tables#12]
To reproduce, inject some non-ascii to the related string, for example for de_DE :

msgid "Bobby Tables: A guide to preventing SQL injection"
msgstr "Bobby Tables: Ein Leitfaden gegen SQL-Einschleusungşığ"

And the header will include some garbage.

No idea how to fix that. I'll instead use html entities for this string in my translation.

**Comment by petdance** [comment]
These translations have been removed.
