### ISSUE TITLE
Consolidate C#, .NET, and ASP pages into single .NET page (with or without subpages)

### ISSUE THREAD

**Issue by zspitz** [petdance/bobby-tables#79]
The information for avoiding SQL injection in .NET is currently fragmented over 3 different pages: [C#](http://bobby-tables.com/csharp), [.NET](http://bobby-tables.com/dotnet), and [ASP](http://bobby-tables.com/asp). It should really be consolidated into a single page (with or without subpages as appropriate), and should be structured as follows:

* Direct ADO.NET
  - Using the base classes in [**System.Data.Common**](https://docs.microsoft.com/en-us/dotnet/api/system.data.common?view=netframework-4.7.2)
  - [Built-in providers](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/data-providers)
    - [SQL Server](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/data-providers#net-framework-data-provider-for-includessnoversionincludesssnoversion-mdmd-sqlclient)
    - [OLE DB](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/data-providers#net-framework-data-provider-for-ole-db)
    - [ODBC](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/data-providers#net-framework-data-provider-for-odbc)
  - Third-party providers
    - [Oracle](http://www.oracle.com/technetwork/topics/dotnet/index-085163.html)
    - Postgresql
    - [MySQL](https://dev.mysql.com/downloads/connector/net/6.10.html)
    - [SQLite](https://system.data.sqlite.org/index.html/doc/trunk/www/index.wiki)
* Entity Framework Core ?
* EF 6
  - [ExecuteSQLCommand](https://msdn.microsoft.com/en-us/library/system.data.entity.database.executesqlcommand(v=vs.113).aspx) and [ExecuteSQLCommandSync](https://msdn.microsoft.com/en-us/library/system.data.entity.database.executesqlcommandasync(v=vs.113).aspx) methods
  - [SqlQuery](https://msdn.microsoft.com/en-us/library/system.data.entity.database.sqlquery(v=vs.113).aspx) method
* Dapper
* Additional ORMs

This information is the same for any .NET language -- C#, VB.NET, F#, IronPython -- and for every .NET programming environment -- ASP.NET, WPF, console application, WinForms. At best it might be good to have examples for various languages on each subsection.

One important note: some providers support named parameters (e.g. the SQL Server provider); some providers support position parameters (e.g. the OLE DB provider).

**Comment by zspitz** [comment]
@petdace I am interested in writing this; I've already written something similar.

I'm just worried that this is too much information to fit on a single page. Do you agree? Or is there some facility for sub-pages?

**Comment by zspitz** [comment]
@petdance I've finally gotten to this, and have a [first draft](https://github.com/zspitz/bobby-tables/blob/dev/s/adodotnet.md). Some points:

* ADO.NET is automatically rendered as a hyperlink, which I've hacked around by writing `ADO<i></i>.NET`. Is this acceptable?
* I've setup two pages: [`adodotnet.md`](https://github.com/zspitz/bobby-tables/blob/dev/s/adodotnet.md) for direct ADO.NET, and ['adodotnet_orm.md`](https://github.com/zspitz/bobby-tables/blob/dev/s/adodotnet_orm.md) for ORMs built on top of ADO.NET such as Entity Framework and Dapper.
* This is still very much a work in progress; should I create a pull request, or should I wait until it's more complete?

If you could take a look and make sure that I'm going in the right direction, I would appreciate it very much.

**Comment by petdance** [comment]
> ADO.NET is automatically rendered as a hyperlink, which I've hacked around by writing ADO<i></i>.NET. Is this acceptable?

Better to just make the cranker just ignore uppercase URL-like things.

Holy cats, that page is great.  More detail than anything I've put together. Thank you.

Two quick things.  First, please remove the `TL;DR` heading.  The summary doesn't need to be labeled as such.

Also, please put a chunk of code in that summary, if you can whittle an example down to a line or three.  The code that you supply is a big part of the value of reading that page, and putting some code up top will encourage the reader to read on to see more code.

> If you could take a look and make sure that I'm going in the right direction, I would appreciate it very much.

Yes, yes, beautiful, yes.  Thank you.

**Comment by zspitz** [comment]
Thanks for your input. I've removed the heading and put up an example. It's not a complete example of accessing data, but only the necessary steps needed to avoid SQL injection.

> More detail than anything I've put together. 

I only hope it's not too much detail. Most of the information is there to hammer home this:

> The shared architecture across providers means that **there is a single common strategy for avoiding SQL injection for all data providers, in all .NET languages.**

**Comment by petdance** [comment]
Can this be closed now?

**Comment by zspitz** [comment]
> Can this be closed now?

I think so. We've reached the goals outlined in the first post of the issue.
