### ISSUE TITLE
Add a page for ActiveX Data Objects

### ISSUE THREAD

**Issue by zspitz** [petdance/bobby-tables#80]
This would be useful for: VBA/VB6, ASP Classic, WSH, VBScript.

**Comment by petdance** [comment]
That sounds great. I'll need someone who's not me to write it, since I don't know anything about the Windows ecosystem. If you're interested in doing so, please comment on this ticket.

**Comment by zspitz** [comment]
I am willing to write this.

**Comment by petdance** [comment]
That sounds great.  Thank you.

**Comment by zspitz** [comment]
Closing as fixed by #93 .
