### ISSUE TITLE
Covert to github pages

### ISSUE THREAD

**Issue by stevedorries** [petdance/bobby-tables#81]
Drop all the build chain for the site, directly host with GitHub and put in a crecord for the domain.

**Comment by petdance** [comment]
What are the benefits of this?

**Comment by zspitz** [comment]
@petdance 

* No build step; instantly live
* No requirement to setup a build environment for testing
* Automatic support of all of GitHub-flavored Markdown
* Advanced GitHub Markdown rendering features, e.g. #90

@dancrumb, you downvoted this; could you elaborate on why?

**Comment by dancrumb** [comment]
Sure.

It had no information about what problem it would solve or what it would improve. It was simply a statement to change the hosting strategy. 

Since resolving this issue would take time and effort and there was no indication of benefit, I felt it was a low quality issue.

**Comment by petdance** [comment]
> * No build step; instantly live on commit

I want a build step so that I can look at the content before publishing.

If our problems with GitHub Markdown a problem, then let's make that a separate ticket, which may or may not have a solution of "change the build process".
