### ISSUE TITLE
Links to ADO.NET ORM page seem to be broken

### ISSUE THREAD

**Issue by zspitz** [petdance/bobby-tables#96]
This: http://bobby-tables.com/adodotnet_orm returns a 404.

**Comment by Matlock42** [comment]
Does it need to be added to the `crank.pl` file so the page appears? Changes made on Aug 14 (commit a0e7cfa5e87091b106e96fead52c2c47dbd16f4f) added the page in question but left out of the crank file apparently on purpose (thus the comment on line 29).

**Comment by petdance** [comment]
I added it to crank in the sidebar.  That's OK for now.  Thanks.
